Logistic Regression 

In [205]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt  
import seaborn as sns 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score,classification_report, confusion_matrix
import joblib


In [206]:
from sklearn.datasets import load_iris

In [207]:
data=load_iris()

In [208]:
data

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

In [209]:
data.target

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [210]:
df = pd.DataFrame(data.data,columns=data.feature_names)

In [211]:
df

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                  5.1               3.5                1.4               0.2
1                  4.9               3.0                1.4               0.2
2                  4.7               3.2                1.3               0.2
3                  4.6               3.1                1.5               0.2
4                  5.0               3.6                1.4               0.2
..                 ...               ...                ...               ...
145                6.7               3.0                5.2               2.3
146                6.3               2.5                5.0               1.9
147                6.5               3.0                5.2               2.0
148                6.2               3.4                5.4               2.3
149                5.9               3.0                5.1               1.8

[150 rows x 4 columns]

In [212]:
df['target']=data.target

In [213]:
df

sepal length (cm)  sepal width (cm)  ...  petal width (cm)  target
0                  5.1               3.5  ...               0.2       0
1                  4.9               3.0  ...               0.2       0
2                  4.7               3.2  ...               0.2       0
3                  4.6               3.1  ...               0.2       0
4                  5.0               3.6  ...               0.2       0
..                 ...               ...  ...               ...     ...
145                6.7               3.0  ...               2.3       2
146                6.3               2.5  ...               1.9       2
147                6.5               3.0  ...               2.0       2
148                6.2               3.4  ...               2.3       2
149                5.9               3.0  ...               1.8       2

[150 rows x 5 columns]

In [214]:
df['target_names'] = df['target'].map({i: name for i, name in enumerate(data.target_names)})

In [215]:
df

sepal length (cm)  sepal width (cm)  ...  target  target_names
0                  5.1               3.5  ...       0        setosa
1                  4.9               3.0  ...       0        setosa
2                  4.7               3.2  ...       0        setosa
3                  4.6               3.1  ...       0        setosa
4                  5.0               3.6  ...       0        setosa
..                 ...               ...  ...     ...           ...
145                6.7               3.0  ...       2     virginica
146                6.3               2.5  ...       2     virginica
147                6.5               3.0  ...       2     virginica
148                6.2               3.4  ...       2     virginica
149                5.9               3.0  ...       2     virginica

[150 rows x 6 columns]

In [216]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column             Non-Null Count  Dtype  
---  ------             --------------  -----  
 0   sepal length (cm)  150 non-null    float64
 1   sepal width (cm)   150 non-null    float64
 2   petal length (cm)  150 non-null    float64
 3   petal width (cm)   150 non-null    float64
 4   target             150 non-null    int64  
 5   target_names       150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [217]:
df.isnull().sum()

sepal length (cm)    0
sepal width (cm)     0
petal length (cm)    0
petal width (cm)     0
target               0
target_names         0
dtype: int64

Binary Class Classifiaction using the Logistic Regerssion 

In [218]:
binary_df=df[df['target']!=2]

In [219]:
binary_df

sepal length (cm)  sepal width (cm)  ...  target  target_names
0                 5.1               3.5  ...       0        setosa
1                 4.9               3.0  ...       0        setosa
2                 4.7               3.2  ...       0        setosa
3                 4.6               3.1  ...       0        setosa
4                 5.0               3.6  ...       0        setosa
..                ...               ...  ...     ...           ...
95                5.7               3.0  ...       1    versicolor
96                5.7               2.9  ...       1    versicolor
97                6.2               2.9  ...       1    versicolor
98                5.1               2.5  ...       1    versicolor
99                5.7               2.8  ...       1    versicolor

[100 rows x 6 columns]

In [220]:
x_binary = binary_df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]

In [221]:
y_binary = binary_df['target']

In [222]:
x_test_binary, x_train_binary, y_test_binary, y_train_binary = train_test_split(x_binary,y_binary,test_size=0.2)

In [223]:
logistic_binary = LogisticRegression()
logistic_binary.fit(x_train_binary,y_train_binary)

LogisticRegression()

In [224]:
prediction = logistic_binary.predict(x_test_binary)

In [225]:
print("Classification report for the bianry class classification of logistic regression: \n", classification_report(y_test_binary, prediction))

Classification report for the bianry class classification of logistic regression: 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00        39
           1       1.00      1.00      1.00        41

    accuracy                           1.00        80
   macro avg       1.00      1.00      1.00        80
weighted avg       1.00      1.00      1.00        80



In [226]:
joblib.dump(logistic_binary,"Logistic_Regression_binary.pkl")

['Logistic_Regression_binary.pkl']

In [227]:
accuracy_score(y_test_binary,prediction)

1.0

In [228]:
confusion_matrix(y_test_binary,prediction)

array([[39,  0],
       [ 0, 41]])

Multi Class Classification using Logistic Regression

In [229]:
x=df[['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']]

In [230]:
y=df['target']

In [231]:
x_train_multi, x_test_multi, y_train_multi, y_test_multi = train_test_split( x , y , test_size = 0.2)

In [232]:
logistic_multi = LogisticRegression(multi_class='ovr', solver="lbfgs", max_iter=2000)

In [233]:
logistic_multi.fit(x_train_multi,y_train_multi)

c:\Users\Deepu\anaconda3\envs\gpu-py310\lib\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='ovr')

In [234]:
prediction = logistic_multi.predict(x_test_multi)

In [235]:
prediction

array([1, 1, 2, 2, 1, 2, 2, 1, 0, 0, 2, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0, 1,
       2, 0, 0, 2, 2, 1, 0, 2])

In [236]:
print("Clasification report on multi class classifiaction using logistic regression : \n" , classification_report(y_test_multi, prediction))

Clasification report on multi class classifiaction using logistic regression : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.90      0.95        10
           2       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [237]:
accuracy_score(y_test_multi,prediction)

0.9666666666666667

In [238]:
logistic_multi2 = LogisticRegression(multi_class='multinomial', solver="lbfgs", max_iter=2000)

In [239]:
logistic_multi2.fit(x_train_multi, y_train_multi)

c:\Users\Deepu\anaconda3\envs\gpu-py310\lib\site-packages\sklearn\linear_model\_logistic.py:1247: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. From then on, it will always use 'multinomial'. Leave it to its default value to avoid this warning.
  warnings.warn(


LogisticRegression(max_iter=2000, multi_class='multinomial')

In [240]:
prediction = logistic_multi2.predict(x_test_multi)

In [241]:
prediction

array([1, 1, 2, 2, 1, 2, 2, 1, 0, 0, 2, 2, 2, 0, 1, 2, 1, 2, 1, 0, 0, 1,
       2, 0, 0, 2, 2, 1, 0, 2])

In [242]:
print("Clasification report on Multinomial Logistic Regression : \n", classification_report(y_test_multi,prediction))

Clasification report on Multinomial Logistic Regression : 
               precision    recall  f1-score   support

           0       1.00      1.00      1.00         8
           1       1.00      0.90      0.95        10
           2       0.92      1.00      0.96        12

    accuracy                           0.97        30
   macro avg       0.97      0.97      0.97        30
weighted avg       0.97      0.97      0.97        30



In [243]:
accuracy_score(y_test_multi,prediction)

0.9666666666666667

In [245]:
joblib.dump(logistic_multi,"Logistic_Regression_Multi.pkl")

['Logistic_Regression_Multi.pkl']